repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/eznix86/python-license
    rev: v1.2.2
    hooks:
      - id: license-headers
        args: [--notice-template, NOTICE.template, --fix, AGPL-3.0-or-later, Bruno Bernard]
        files: (\.(go|ts|tsx|py|js|jsx|html|css|vue|sql)|Dockerfile|compose.yaml)$
        pass_filenames: true
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: go-fmt
        name: Run go fmt
        entry: bash -c 'go fmt ./...'
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: lint
        name: Run lint
        entry: bash -c 'bun run lint'
        language: system
        stages: [pre-commit]
