# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025  Bruno Bernard

services:
  app:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
