name: Weekly Release

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type (major, minor, patch)'
        default: ''

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create tag
        run: bash .github/scripts/create-tag.sh
        env:
          VERSION_BUMP: ${{ github.event.inputs.version_bump }}